// Simple static pack builder (Behavior Pack) for Bedrock structure worldgen.
// Note: This is an MVP; you can expand UI and add more worldgen options.

const drop = document.getElementById("drop");
const fileInput = document.getElementById("fileInput");
const tbody = document.querySelector("#table tbody");

const packNameEl = document.getElementById("packName");
const namespaceEl = document.getElementById("namespace");
const buildBtn = document.getElementById("buildBtn");

let files = []; // { file: File, id: string, biome: string, chance: number, rotation: string }

function safeIdFromFilename(name) {
  return name
    .replace(/\.mcstructure$/i, "")
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

function uuidv4() {
  // crypto-based UUID (supported in modern browsers)
  return crypto.randomUUID();
}

function renderTable() {
  tbody.innerHTML = "";
  for (const item of files) {
    const tr = document.createElement("tr");

    tr.innerHTML = `
      <td>${item.file.name}</td>
      <td><input data-k="id" value="${item.id}" /></td>
      <td>
        <select data-k="biome">
          <option value="overworld" ${item.biome === "overworld" ? "selected" : ""}>Overworld (tag)</option>
          <option value="plains_only" ${item.biome === "plains_only" ? "selected" : ""}>Plains only</option>
          <option value="desert_only" ${item.biome === "desert_only" ? "selected" : ""}>Desert only</option>
        </select>
      </td>
      <td><input data-k="chance" type="number" min="1" value="${item.chance}" style="width:110px" /></td>
      <td>
        <select data-k="rotation">
          <option value="random" ${item.rotation === "random" ? "selected" : ""}>Random</option>
          <option value="north" ${item.rotation === "north" ? "selected" : ""}>North</option>
          <option value="east" ${item.rotation === "east" ? "selected" : ""}>East</option>
          <option value="south" ${item.rotation === "south" ? "selected" : ""}>South</option>
          <option value="west" ${item.rotation === "west" ? "selected" : ""}>West</option>
        </select>
      </td>
    `;

    // wire inputs
    tr.querySelectorAll("input,select").forEach((el) => {
      el.addEventListener("input", () => {
        const k = el.dataset.k;
        if (k === "chance") item.chance = Math.max(1, parseInt(el.value || "1", 10));
        else item[k] = el.value;
      });
    });

    tbody.appendChild(tr);
  }
}

function addFiles(fileList) {
  for (const f of fileList) {
    if (!f.name.toLowerCase().endsWith(".mcstructure")) continue;
    files.push({
      file: f,
      id: safeIdFromFilename(f.name),
      biome: "overworld",
      chance: 20,
      rotation: "random",
    });
  }
  renderTable();
}

// Drag & drop
drop.addEventListener("dragover", (e) => { e.preventDefault(); drop.style.opacity = "0.7"; });
drop.addEventListener("dragleave", () => { drop.style.opacity = "1"; });
drop.addEventListener("drop", (e) => {
  e.preventDefault();
  drop.style.opacity = "1";
  addFiles(e.dataTransfer.files);
});

// File picker
fileInput.addEventListener("change", () => addFiles(fileInput.files));

function biomeFilterFor(mode) {
  if (mode === "plains_only") {
    return [{ test: "is_biome", operator: "==", value: "minecraft:plains" }];
  }
  if (mode === "desert_only") {
    return [{ test: "is_biome", operator: "==", value: "minecraft:desert" }];
  }
  // default: overworld tag
  return [{ test: "has_biome_tag", operator: "==", value: "overworld" }];
}

function makeManifest(packName) {
  const headerUuid = uuidv4();
  const moduleUuid = uuidv4();

  return {
    format_version: 2,
    header: {
      name: packName,
      description: "Generated by Structure Spawner Pack Builder",
      uuid: headerUuid,
      version: [1, 0, 0],
      min_engine_version: [1, 20, 0]
    },
    modules: [
      {
        type: "data",
        uuid: moduleUuid,
        version: [1, 0, 0]
      }
    ]
  };
}

function makeFeature(ns, id) {
  return {
    format_version: "1.13.0",
    "minecraft:structure_feature": {
      description: { identifier: `${ns}:${id}_feature` },
      structure_name: id,                 // matches structures/<id>.mcstructure name
      adjustment_radius: 8,
      facing_direction: "random"
    }
  };
}

function makeFeatureRule(ns, id, biomeMode, chance, rotation) {
  // rotation: we keep the feature random, but you can also hard-set facing_direction in makeFeature if you prefer fixed.
  // Here we show rotation as UI, but simplest: if not random, you can swap facing_direction in the feature.
  return {
    format_version: "1.13.0",
    "minecraft:feature_rules": {
      description: {
        identifier: `${ns}:${id}_rule`,
        places_feature: `${ns}:${id}_feature`
      },
      conditions: {
        placement_pass: "surface_pass",
        minecraft:biome_filter: biomeFilterFor(biomeMode)
      },
      distribution: {
        iterations: 1,
        scatter_chance: chance,
        x: 0,
        z: 0,
        y: "query.heightmap(variable.worldx, variable.worldz)"
      }
    }
  };
}

buildBtn.addEventListener("click", async () => {
  if (files.length === 0) {
    alert("Add at least one .mcstructure file first!");
    return;
  }

  const packName = packNameEl.value.trim() || "My Structure Spawner Pack";
  const ns = (namespaceEl.value.trim() || "custom").toLowerCase();

  const zip = new JSZip();

  // files
  zip.file("manifest.json", JSON.stringify(makeManifest(packName), null, 2));

  const structuresFolder = zip.folder("structures");
  const featuresFolder = zip.folder("worldgen/features");
  const rulesFolder = zip.folder("worldgen/feature_rules");

  for (const item of files) {
    const id = item.id || safeIdFromFilename(item.file.name);

    // Put structure file with exact name expected by structure_name
    const buf = await item.file.arrayBuffer();
    structuresFolder.file(`${id}.mcstructure`, buf);

    // Feature + Rule
    featuresFolder.file(`${id}_feature.json`, JSON.stringify(makeFeature(ns, id), null, 2));
    rulesFolder.file(`${id}_rule.json`, JSON.stringify(
      makeFeatureRule(ns, id, item.biome, item.chance, item.rotation),
      null, 2
    ));
  }

  const blob = await zip.generateAsync({ type: "blob" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = `${packName.replace(/[^a-z0-9_-]+/gi, "_")}.zip`;
  a.click();
  URL.revokeObjectURL(a.href);
});
